### PR TITLE
Ignore error DTD_ID_REDEFINED in html4 + add xhtml extension

### PR DESCRIPTION
**Pull request by rtonsing**

### CODE REVIEW

**Comment by srjfoo** [comment]
Sandbox [here](https://www.pgdp.org/~srjfoo/ppwb/ppcomp.php).

-----

Just as a general comment and irrelevant to this PR, would it be a good idea to echo any error messages that are now written to `messages.log` if there are any?

Currently, if there are error messages, all the user gets is a reference code -- and they either have to know what to go looking for, or ask someone to look it up for them. If there's a good reason for this approach, that's fine; I just thought I'd ask. It might be more helpful of they saw the error messages directly?

**Review by srjfoo — APPROVED** [review]

**Comment by cpeel** [comment]
> Just as a general comment and irrelevant to this PR, would it be a good idea to echo any error messages that are now written to `messages.log` if there are any?

For ppwb this approach was done from a security stance to help prevent leaking sensitive information to the user. We don't hide entirely (because someone who knows can just look at `messages.log` but the idea is for the tool to output to `stdout` anything they want the user to see and `stderr` things that admins and other squirrels should see.

**Comment by srjfoo** [comment]
> > Just as a general comment and irrelevant to this PR, would it be a good idea to echo any error messages that are now written to `messages.log` if there are any?
> 
> For ppwb this approach was done from a security stance to help prevent leaking sensitive information to the user. We don't hide entirely (because someone who knows can just look at `messages.log` but the idea is for the tool to output to `stdout` anything they want the user to see and `stderr` things that admins and other squirrels should see.

Thanks -- I've got a long way to go before I understand more than just how to test the issue at hand! 🙂

**Review by windymilla — APPROVED** [review]
Looks good, thanks

**Comment by asylumcs** [comment]
Seems ok to me.

**Pull request merged**
